spring:
  application:
    name: ms-user-management
  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
  cloud:
    discovery:
      enabled: true
    loadbalancer:
      ribbon:
        enabled: true

auto-spare:
  scm:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/autosparescm
      driver-class-name: com.mysql.cj.jdbc.Driver

server:
  servlet:
    context-path: /usermanagementservices

springdoc:
  api-docs:
    enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8041/eureka/


